### ISSUE TITLE
OmniRom 6.0 Moto G XT1032 [No Mobile Data]

### ISSUE THREAD

**Issue by jonobrien1** [xc-racer99/android_device_motorola_falcon#7]
Omnirom Marshmallow installed on Moto G 1st Gen [XT1032]. All working fine except for Mobile Data. I've no internet connection when not on WiFi. Anyone got a solution? Thanks.

**Comment by xc-racer99** [comment]
Hmm, I haven't tested Mobile Data lately as its not my main device.  Have you checked your APN settings?  Also, what carrier and does MMS work?

I'll try to test again on my own XT1032 and see how it goes...

**Comment by jonobrien1** [comment]
Issue solved! It was in fact my APN settings. Had to manually input the data. Found the info I needed on my carrier's web site. Thanks for the comment xc-racer99.
